Resources:
  CoaidDonationHistoryBucket8D2E544D:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: coaid.donation.history-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CoaidInfraStack/CoaidDonationHistoryBucket/Resource
  DonationsTable5264C194:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: donation_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: donation_id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: donations
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CoaidInfraStack/DonationsTable/Resource
  insertDonationLambdaServiceRoleB0FD0B6D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CoaidInfraStack/insertDonationLambda/ServiceRole/Resource
  insertDonationLambdaServiceRoleDefaultPolicy6B9EBED6:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:*
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - CoaidDonationHistoryBucket8D2E544D
                - Arn
          - Action: dynamodb:*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - DonationsTable5264C194
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: insertDonationLambdaServiceRoleDefaultPolicy6B9EBED6
      Roles:
        - Ref: insertDonationLambdaServiceRoleB0FD0B6D
    Metadata:
      aws:cdk:path: CoaidInfraStack/insertDonationLambda/ServiceRole/DefaultPolicy/Resource
  insertDonationLambda4A002361:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters72d2504449e06992eca1b537c17ecd008a2c6f0af2d7c6741901083ad1f334d7S3Bucket3582A5BD
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters72d2504449e06992eca1b537c17ecd008a2c6f0af2d7c6741901083ad1f334d7S3VersionKey6685A8C5
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters72d2504449e06992eca1b537c17ecd008a2c6f0af2d7c6741901083ad1f334d7S3VersionKey6685A8C5
      Role:
        Fn::GetAtt:
          - insertDonationLambdaServiceRoleB0FD0B6D
          - Arn
      Environment:
        Variables:
          DONATION_TABLE_NAME:
            Ref: DonationsTable5264C194
          DONATION_HISTORY_BUCKET_NAME:
            Ref: CoaidDonationHistoryBucket8D2E544D
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.insertDonationData
      Runtime: nodejs14.x
    DependsOn:
      - insertDonationLambdaServiceRoleDefaultPolicy6B9EBED6
      - insertDonationLambdaServiceRoleB0FD0B6D
    Metadata:
      aws:cdk:path: CoaidInfraStack/insertDonationLambda/Resource
      aws:asset:path: asset.72d2504449e06992eca1b537c17ecd008a2c6f0af2d7c6741901083ad1f334d7
      aws:asset:property: Code
  CoaidApiGatewayBDD70117:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      CorsConfiguration:
        AllowMethods:
          - "*"
        AllowOrigins:
          - "*"
      Name: coaid-api
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: CoaidInfraStack/CoaidApiGateway/Resource
  CoaidApiGatewayDefaultStage5F1C33FF:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: CoaidApiGatewayBDD70117
      StageName: $default
      AutoDeploy: true
    Metadata:
      aws:cdk:path: CoaidInfraStack/CoaidApiGateway/DefaultStage/Resource
  CoaidApiGatewayGETinsertdonationCoaidInfraStackCoaidApiGatewayGETinsertdonation184107D2PermissionB700BFBB:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - insertDonationLambda4A002361
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: CoaidApiGatewayBDD70117
            - /*/*/insert-donation
    Metadata:
      aws:cdk:path: CoaidInfraStack/CoaidApiGateway/GET--insert-donation/CoaidInfraStackCoaidApiGatewayGETinsertdonation184107D2-Permission
  CoaidApiGatewayGETinsertdonationHttpIntegration9e9f109d4b90654b288fb7937f0d9991BB0ABEA7:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: CoaidApiGatewayBDD70117
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - insertDonationLambda4A002361
          - Arn
      PayloadFormatVersion: "2.0"
    Metadata:
      aws:cdk:path: CoaidInfraStack/CoaidApiGateway/GET--insert-donation/HttpIntegration-9e9f109d4b90654b288fb7937f0d9991/Resource
  CoaidApiGatewayGETinsertdonationA934A8BF:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: CoaidApiGatewayBDD70117
      RouteKey: GET /insert-donation
      AuthorizationType: NONE
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: CoaidApiGatewayGETinsertdonationHttpIntegration9e9f109d4b90654b288fb7937f0d9991BB0ABEA7
    Metadata:
      aws:cdk:path: CoaidInfraStack/CoaidApiGateway/GET--insert-donation/Resource
  CoaidApiGatewayPOSTinsertdonationCoaidInfraStackCoaidApiGatewayPOSTinsertdonationFFEEF3AFPermission4C1B7E15:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - insertDonationLambda4A002361
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: CoaidApiGatewayBDD70117
            - /*/*/insert-donation
    Metadata:
      aws:cdk:path: CoaidInfraStack/CoaidApiGateway/POST--insert-donation/CoaidInfraStackCoaidApiGatewayPOSTinsertdonationFFEEF3AF-Permission
  CoaidApiGatewayPOSTinsertdonation2F026F7A:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: CoaidApiGatewayBDD70117
      RouteKey: POST /insert-donation
      AuthorizationType: NONE
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: CoaidApiGatewayGETinsertdonationHttpIntegration9e9f109d4b90654b288fb7937f0d9991BB0ABEA7
    Metadata:
      aws:cdk:path: CoaidInfraStack/CoaidApiGateway/POST--insert-donation/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE11RwU7DMAz9Fu6pt7JxZ0ya4AJT4Qe8NFRpm6SKnU1VlH+nSWEHTu/ZeX5+Vmqot3vYPjzjjSrZDpsonVcQPxnlII7OEvsgWRy/7UfgKbBoFLngpRIHIsWLrtO2y+9n9GgUK5+Lu2rhi0urWTubRN4SaQfxJchBFduVJdHOFo1rLxC/8DKWwUKSGNFcWqysa1VP8F7gFKzMlkKjgdi4daDg2Y1aziVRYUnQrsIclqBk/jWEuEjuPlmuvNFEa9BJd8jqhvP1EeIr83SYdBZlyGU+vOxcSW41LvDK3iyrzuOf8b+y6FJKIl8EPW2u9R7qp+UXetK68sGyNgqaFX8ASQ6xaqIBAAA=
    Metadata:
      aws:cdk:path: CoaidInfraStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  BucketNameExport:
    Value:
      Ref: CoaidDonationHistoryBucket8D2E544D
    Export:
      Name: CoaidDonationHistoryBucketName
  InsertDonationAPI:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: CoaidApiGatewayBDD70117
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
    Export:
      Name: InsertDonationAPIName
Parameters:
  AssetParameters72d2504449e06992eca1b537c17ecd008a2c6f0af2d7c6741901083ad1f334d7S3Bucket3582A5BD:
    Type: String
    Description: S3 bucket for asset "72d2504449e06992eca1b537c17ecd008a2c6f0af2d7c6741901083ad1f334d7"
  AssetParameters72d2504449e06992eca1b537c17ecd008a2c6f0af2d7c6741901083ad1f334d7S3VersionKey6685A8C5:
    Type: String
    Description: S3 key for asset version "72d2504449e06992eca1b537c17ecd008a2c6f0af2d7c6741901083ad1f334d7"
  AssetParameters72d2504449e06992eca1b537c17ecd008a2c6f0af2d7c6741901083ad1f334d7ArtifactHashF895528A:
    Type: String
    Description: Artifact hash for asset "72d2504449e06992eca1b537c17ecd008a2c6f0af2d7c6741901083ad1f334d7"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

